config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :people, only: [:create]

end

app/models/person.rb
class Person < ActiveRecord::Base

  enum status: { created: 0, emailed: 1}

  validates :name, :phone, :email, presence: true
  validates :phone, :email, uniqueness: true	
	
  FIELDS = {email_fields: ["name", "phone", "email", "description"]}

  def email_details
	self.attributes.select{|k,v| FIELDS[:email_fields].include?(k)}
  end			

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
	def create
		@person = Person.new person_params
		if @person.save
		  WebMailer.contacted_us(@person).deliver
		  @person.emailed!		
		  render nothing: true, status: 200	
		else
		  raise "some error"			
		end
	end

	private

	def person_params
		params.permit(:name, :phone, :email, :description)
	end	
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@person = Person.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SuccessGroup</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body id="page-top" class="index">

    <%= yield %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
</body>
</html>

app/views/welcome/_about.html.erb
<!-- About Section -->
<section id="about">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h2 class="section-heading">About</h2>
        <h3 class="section-subheading text-muted">“The world is a book, and those who do not travel read only one page.” – Saint Augustine</h3>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-12">
        <ul class="timeline">
          <li>
            <div class="timeline-image">
              <img class="img-circle img-responsive full-height" src="/assets/travel_free.jpg" alt="">
            </div>
            <div class="timeline-panel">
              <div class="timeline-heading">
                <h4>Free!</h4>
                <h4 class="subheading">Free! Free!</h4>
              </div>
              <div class="timeline-body">
                <p class="text-muted">Travel The Globe For Free is owned and founded and operated by Weapon Of Success Group International, as a free resource to help ordinary people that can't afford to travel to their dream destination due to inadequate finance!</p>
              </div>
            </div>
          </li>
          <li class="timeline-inverted">
            <div class="timeline-image">
              <img class="img-circle img-responsive full-height" src="/assets/dream_destination.jpg" alt="">
            </div>
            <div class="timeline-panel">
              <div class="timeline-heading">
                <h4>Group</h4>
                <h4 class="subheading">Weapon Of Success Group International</h4>
              </div>
              <div class="timeline-body">
                <p class="text-muted">''Weapon Of Success Group International'' will be the first and only group to start and run a %100 free travelling worldwide to the public without paying a damn!</p>
              </div>
            </div>
          </li>
          <li>
            <div class="timeline-image">
              <img class="img-circle img-responsive full-height" src="/assets/world_tour.jpg" alt="">
            </div>
            <div class="timeline-panel">
              <div class="timeline-heading">
                <h4>Collect Moments Not Things</h4>
                <h4 class="subheading">Across The Globe</h4>
              </div>
              <div class="timeline-body">
                <p class="text-muted">Our primary aim is to help all shades of persons across the globe to travel to their dream holiday destination for FREE!</p>
              </div>
            </div>
          </li>
          <li class="timeline-inverted">
            <div class="timeline-image">
              <img class="img-circle img-responsive full-height" src="/assets/travel.jpg" alt="">
            </div>
            <div class="timeline-panel">
              <div class="timeline-heading">
                <h4>2017</h4>
                <h4 class="subheading">Explore The Beauty</h4>
              </div>
              <div class="timeline-body">
                <p class="text-muted">Yes for FREE I repeat, without paying a damn! Our target is to start with at-least 100 people from every part of the world to travel and explore the beauty of world before the end of the year 2017!</p>
              </div>
            </div>
          </li>
          <li class="timeline-inverted">
            <div class="timeline-image">
              <h4>Live
                <br>Your
                <br>Life!</h4>
            </div>
          </li>
        </ul>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-12 text-center">
        <p class="text-muted">After a fair share of setbacks, a ton of testing and our team working round the clock we're pleased to announce we are officially out to public today September 1st, 2016. If you are among the individual that want to travel abroad for vacation but can't afford it, we are the solution. Travel The Globe For Free is for those that can't afford to travel to their dream holiday destination and opportunity for regular travellers to travel For Free to their next dream holiday destination without paying a cent on your travelling expenses. We believe in action, contact us for more information.</p>
      </div>
    </div>
  </div>
</section>

app/views/welcome/_contact.html.erb
<!-- Contact Section -->
<section id="contact">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h2 class="section-heading">Contact Us</h2>
        <h3 class="section-subheading text-muted">“I haven’t been everywhere, but it’s on my list.” – Susan Sontag.</h3>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-12">
        <form name="sentMessage" action="<%= people_path %>" method="post" id="contactForm" novalidate>
          <div class="row">
            <div class="col-md-6">
              <div class="form-group">
                <input type="text" class="form-control" placeholder="Your Name *" id="name" required data-validation-required-message="Please enter your name.">
                <p class="help-block text-danger"></p>
              </div>
              <div class="form-group">
                <input type="email" class="form-control" placeholder="Your Email *" id="email" required data-validation-required-message="Please enter your email address.">
                <p class="help-block text-danger"></p>
              </div>
              <div class="form-group">
                <input type="tel" class="form-control" placeholder="Your Phone *" id="phone" required data-validation-required-message="Please enter your phone number.">
                <p class="help-block text-danger"></p>
              </div>
            </div>
            <div class="col-md-6">
              <div class="form-group">
                <textarea class="form-control" placeholder="Your Message *" id="message" required data-validation-required-message="Please enter a message."></textarea>
                <p class="help-block text-danger"></p>
              </div>
            </div>
            <div class="clearfix"></div>
            <div class="col-lg-12 text-center">
              <div id="success"></div>
              <button type="submit" class="btn btn-xl" id="contact_me_submit">Send Message</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</section>

app/views/welcome/_footer.html.erb
<footer>
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <span class="copyright">Copyright &copy; Success Group 2016</span>
      </div>
      <div class="col-md-4">
        <ul class="list-inline social-buttons">
          <li><a href="#"><i class="fa fa-twitter"></i></a>
          </li>
          <li><a href="#"><i class="fa fa-facebook"></i></a>
          </li>
          <li><a href="#"><i class="fa fa-linkedin"></i></a>
          </li>
        </ul>
      </div>
      <div class="col-md-4">
        <ul class="list-inline quicklinks">
          <li><a href="#">Privacy Policy</a>
          </li>
          <li><a href="#">Terms of Use</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</footer>

app/views/welcome/_header.html.erb
<!-- Header -->
<header>
  <div class="container">
    <div class="intro-text">
      <div class="intro-lead-in">Travel The Globe!</div>
      <div class="intro-heading">Weapon Of Success Group International</div>
      <a href="#services" class="page-scroll btn btn-xl">Tell Me More</a>
    </div>
  </div>
</header>

app/views/welcome/_nav.html.erb
<!-- Navigation -->
<nav id="mainNav" class="navbar navbar-default navbar-custom navbar-fixed-top">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header page-scroll">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
      </button>
      <a class="navbar-brand page-scroll" href="#page-top">Dream Holiday</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li class="hidden">
          <a href="#page-top"></a>
        </li>
        <li>
          <a class="page-scroll" href="#services">Services</a>
        </li>
        <li>
          <a class="page-scroll" href="#about">About</a>
        </li>
        <li>
          <a class="page-scroll" href="#contact">Contact</a>
        </li>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container-fluid -->
</nav>

app/views/welcome/_services.html.erb
<!-- Services Section -->
<section id="services">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h2 class="section-heading">Services</h2>
        <h3 class="section-subheading text-muted">Travel The Globe For Free is owned and founded and operated by Weapon Of Success Group International, as a free resource to help ordinary people.</h3>
      </div>
    </div>
    <div class="row text-center">
      <div class="col-md-4">
                    <span class="fa-stack fa-4x">
                        <i class="fa fa-circle fa-stack-2x text-primary"></i>
                        <i class="fa fa-plane fa-stack-1x fa-inverse"></i>
                    </span>
        <h4 class="service-heading">Travel Free</h4>
        <p class="text-muted">100% free travelling worldwide to the public without paying a damn.</p>
      </div>
      <div class="col-md-4">
                    <span class="fa-stack fa-4x">
                        <i class="fa fa-circle fa-stack-2x text-primary"></i>
                        <i class="fa fa-train fa-stack-1x fa-inverse"></i>
                    </span>
        <h4 class="service-heading">Dream Destination</h4>
        <p class="text-muted">Help all shades of persons across the globe to travel to their dream holiday destination.</p>
      </div>
      <div class="col-md-4">
                    <span class="fa-stack fa-4x">
                        <i class="fa fa-circle fa-stack-2x text-primary"></i>
                        <i class="fa fa-map fa-stack-1x fa-inverse"></i>
                    </span>
        <h4 class="service-heading">World Tour</h4>
        <p class="text-muted">"The gladdest moment in human life, me thinks, is a departure into unknown lands." – Sir Richard Burton</p>
      </div>
    </div>
  </div>
</section>

app/views/welcome/index.html.erb
<%= render 'nav' %>

<%= render 'header' %>

<%= render 'services' %>

<%= render 'about' %>

<%= render 'contact' %>

<%= render 'footer' %>